# Base image
# Digest: sha256:59812c19504546fc66b0b26722bf0754ee48b74f9abc5ed9c3f251fc45d86099
FROM node:16.17.0-bullseye-slim

# Optimize Node.js tooling for production
ENV NODE_ENV production
# Install pm2
RUN npm install pm2 -g
# Create app directory
WORKDIR /usr/src/app

# Copy files
COPY --chown=node:node dist /usr/src/app

# Install app dependencies
RUN yarn install

# Don't run nodejs app as root
USER node

# Run application
CMD ["pm2-runtime", "pm2-process.json"]
